[package]
name = "cmcc-fucker"
version = "0.1.0"
edition = "2021"

[dependencies]
guid-create = "0.3.1"
windows = { version = "0.52.0", features = ["Win32_System_Com"] }

[profile.release]
lto = false
opt-level = "z"